=== Domcik8/University/Interneto technologijos/Schema.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns="galaxies"
           xmlns:gl="galaxies"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="galaxies"
           elementFormDefault="qualified">

  <xs:element name="galaxy" type="GalaxyType">
    <xs:key name="PlanetNameKey">
      <xs:selector xpath="gl:star/gl:planet"/>
      <xs:field xpath="@name"/>
    </xs:key>

    <xs:keyref name="PlanetListKeyRef" refer="PlanetNameKey">
      <xs:selector xpath="gl:star/gl:uzd0"/>
      <xs:field xpath="."/>
    </xs:keyref>
  </xs:element>


  <xs:element name="mass" type="xs:float"/>
  
  <xs:element name="star_quantity" type="xs:integer"/>
  <xs:element name="star" type="StarType"/>
  <xs:element name="blackhole_quantity" type="xs:integer"/>

  <xs:complexType name="GalaxyType">
    <xs:sequence>
      <xs:element ref="star_quantity"/>
      <xs:element ref="star" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute name="name" type="xs:string" use="required"/>
  </xs:complexType>
  
  <xs:complexType name="StarType">
    <xs:sequence>
      <xs:element ref="mass"/>
      <xs:element name="planet_quantity" type="xs:integer"/>
      <xs:element name="planet" type="PlanetTypeMixed" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="uzd0" type="SolarPlanetName" minOccurs="0"/>
      <xs:element name="uzd1" type="PlanetTypeType" minOccurs="0"/>
      <xs:element name="uzd1.1" type="MassUnitType" minOccurs="0"/>
      <xs:element name="uzd2" type="PlanetListType" minOccurs="0"/>
      <xs:element name="uzd3.1" type="PowerIntervalMassUnitType" minOccurs="0"/>
      <xs:element name="uzd3.2" type="IntervalMassUnitType" minOccurs="0"/>
      <xs:element name="uzd4.1" type="SuperGalaxyType" minOccurs="0"/>
      <xs:element name="uzd4.2" type="GalaxyQuantitiesType" minOccurs="0"/>
       



    </xs:sequence>
    <xs:attribute name="name" type="xs:string"/>
  </xs:complexType>

  <!--choice valdymo struktūra-->
  <xs:complexType name="PlanetType">
    <xs:sequence>
      <xs:choice>
          <xs:element name="discoverer" type="xs:string" minOccurs="0"/>
      </xs:choice>
      <xs:element ref="mass"/>
      <xs:element name="satelite_quantity" type="xs:integer"/>
        <xs:choice>
          <xs:sequence>
            <xs:element name="continent_quantity" type="xs:integer" minOccurs="0"/>
            <xs:element name="continent" type="ContinentType" minOccurs="0" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:choice>
        <xs:choice>
          <xs:element name="satelite" type="SateliteType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:choice>
    </xs:sequence>
    <xs:attribute name="name" type="SolarPlanetName"/>
    <xs:attribute name="type" type="PlanetTypeType"/>
    <xs:attribute name="discovered" type="xs:string"/>
    <xs:attribute name="population" type="xs:string"/>
  </xs:complexType>

  <xs:complexType name="ContinentType">
    <xs:attribute name="name" type="xs:string"/>
  </xs:complexType>

  <xs:complexType name="SateliteType">
    <xs:sequence>
      <xs:element ref="mass"/>
    </xs:sequence>
    <xs:attribute name="name" type="xs:string"/>
  </xs:complexType>
  
 <xs:simpleType name="SolarPlanetName">
  <xs:restriction base="xs:string">
      <xs:enumeration value="Mercury"/>
      <xs:enumeration value="Venus"/>
      <xs:enumeration value="Earth"/>
      <xs:enumeration value="Mars"/>
      <xs:enumeration value="Jupiter"/>
      <xs:enumeration value="Saturn"/>
      <xs:enumeration value="Uranus"/>
      <xs:enumeration value="Neptune"/>
  </xs:restriction>
 </xs:simpleType>

  <!--Paprastas tipas-->
  <xs:simpleType name="PlanetTypeType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Terrestrial planet"/>
      <xs:enumeration value="Giant planet"/>
    </xs:restriction>
  </xs:simpleType>

<!--Paprastas tipas-->
  <xs:simpleType name="MassUnitType">
    <xs:restriction base="xs:decimal">
      <xs:fractionDigits value="10"/>
    </xs:restriction>
  </xs:simpleType>
  
<!--Sąrašo tipas-->
  <xs:simpleType name="PlanetListType">
    <xs:list itemType="SolarPlanetName"/>
  </xs:simpleType>

<!--Sudėtingi tipai su paprastu turiniu extension-->
  <xs:complexType name="PowerIntervalMassUnitType">
    <xs:simpleContent>
      <xs:extension base="MassUnitType">
        <xs:attribute name="power" type="xs:integer"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  
<!--Sudėtingi tipai su paprastu turiniu restriction-->
  <xs:complexType name="IntervalMassUnitType">
    <xs:simpleContent>
      <xs:restriction base="PowerIntervalMassUnitType">
        <xs:maxInclusive value="1000000000"/>
      </xs:restriction>
    </xs:simpleContent>
  </xs:complexType>

<!-- Sudėtingi tipai su sudėtingu turiniu extension-->
  <xs:complexType name="SuperGalaxyType">
    <xs:complexContent>
      <xs:extension base="GalaxyType">
        <xs:sequence>
          <xs:element ref="blackhole_quantity"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  
<!--Sudėtingi tipai su sudėtingu turiniu restriction-->
  <xs:complexType name="GalaxyQuantitiesType">
    <xs:complexContent>
      <xs:restriction base="SuperGalaxyType">
        <xs:sequence>
          <xs:element ref="star_quantity"/>
          <xs:element ref="blackhole_quantity"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required"/>
      </xs:restriction>
    </xs:complexContent>
  </xs:complexType>

<!--Sudėtingi tipai su sudėtingu turiniu restriction-->
<xs:complexType name="GalaxyQuantitiesTypeApribojimopricipas">
  <xs:complexContent>
    <xs:restriction base="SuperGalaxyType">
      <xs:sequence>
        <xs:element ref="star_quantity"/>
        <xs:element ref="blackhole_quantity"/>
      </xs:sequence>
      <!--<xs:attribute name="name" type="xs:string" use="prohibited"/>-->
    </xs:restriction>
  </xs:complexContent>
</xs:complexType>

<!--Sudėtingas tipas su mišriu turiniu-->
  <xs:complexType name="PlanetTypeMixed" mixed="true">
    <xs:sequence>
      <xs:choice>
        <xs:element name="discoverer" type="xs:string" minOccurs="0"/>
      </xs:choice>
      <xs:element ref="mass"/>
      <xs:element name="satelite_quantity" type="xs:integer"/>
      <xs:choice>
        <xs:sequence>
          <xs:element name="continent_quantity" type="xs:integer" minOccurs="0"/>
          <xs:element name="continent" type="ContinentType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
      </xs:choice>
      <xs:choice>
        <xs:element name="satelite" type="SateliteType" minOccurs="0" maxOccurs="unbounded"/>
      </xs:choice>
    </xs:sequence>
    <xs:attribute name="name" type="SolarPlanetName"/>
    <xs:attribute name="type" type="PlanetTypeType"/>
    <xs:attribute name="discovered" type="xs:string"/>
    <xs:attribute name="population" type="xs:string"/>
  </xs:complexType>
  
</xs:schema>

=== Domcik8/University/Interneto technologijos/XML.xml
<?xml version="1.0" encoding="utf-8"?>
<galaxy name='Milky Way' xmlns='galaxies'
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="Schema.xsd">
  <star_quantity>300000000000</star_quantity>
  <star name='Sun'>
    <mass>19885500</mass>
    <planet_quantity>8</planet_quantity>
    <planet name='Mercury' type='Terrestrial planet'>
      <mass>3.3022</mass>
      <satelite_quantity>0</satelite_quantity>
    </planet>
    <planet name='Venus' type='Terrestrial planet'>
      <mass>48.676</mass>
      <satelite_quantity>0</satelite_quantity>
    </planet>
    <planet name='Earth' type='Terrestrial planet' population='7.3 billion'>
      <mass>59.7219</mass>
      <satelite_quantity>1</satelite_quantity>
      <continent_quantity>7</continent_quantity>
      <continent name='Asia'></continent>
      <continent name='Africa'></continent>
      <continent name='North America'></continent>
      <continent name='South America'></continent>
      <continent name='Antarctica'></continent>
      <continent name='Europe'></continent>
      <continent name='Australia'></continent>
      <satelite name='Moon'>
        <mass>0.73477</mass>
      </satelite>
    </planet>
    <planet name='Mars' type='Terrestrial planet'>
      <mass>6.4185</mass>
      <satelite_quantity>2</satelite_quantity>
    </planet>
    <planet name='Jupiter' type='Giant planet'>
      <mass>18986</mass>
      <satelite_quantity>67</satelite_quantity>
      <satelite name='Io'>
        <mass>0.8931938</mass>
      </satelite>
      <satelite name='Europa'>
        <mass>0.4799844</mass>
      </satelite>
      <satelite name='Ganymede'>
        <mass>1.4819</mass>
      </satelite>
      <satelite name='Callisto'>
        <mass>1.075938</mass>
      </satelite>
    </planet>
    <planet name='Saturn' type='Giant planet'>
      <mass>5684.6</mass>
      <satelite_quantity>65</satelite_quantity>
    </planet>
    <planet name='Uranus' type='Giant planet'>
      <mass>868.10</mass>
      <satelite_quantity>27</satelite_quantity>
    </planet>
    <planet name='Neptune' type='Giant planet' discovered='23 September 1846'>
      <discoverer>Urbain Le Verrier, Johann Galle</discoverer>
      <mass>1024.3</mass>
      <satelite_quantity>14</satelite_quantity>
    </planet>
  
    <!--Papildomi testai uzduotims
    <uzd0>Neptune</uzd0>
    <uzd1>Terrestrial planet</uzd1>
    <uzd1.1>154.1234567890</uzd1.1>
    <uzd2>Mercury Earth Neptune</uzd2>
    <uzd3.1 power='5'>15.15</uzd3.1>
    <uzd3.2 power='10'>22222222222</uzd3.2>
    <uzd4.1 name='4.1'>
      <star_quantity>1</star_quantity>
      <star>
        <mass>124</mass>
        <planet_quantity>0</planet_quantity>
      </star>
      <blackhole_quantity>4</blackhole_quantity>
    </uzd4.1>
    <uzd4.2 name='4.2'>
      <star_quantity>12</star_quantity>
      <blackhole_quantity>4</blackhole_quantity>
    </uzd4.2>-->
    
  
  </star>
</galaxy>
